<?php

return [

    /**
     * Your Plain workspace's global HMAC secret.
     *
     * This secret can be viewed and (re)generated by Plain workspace admins in Settings → Request signing.
     * This will be used to verify that request were made by Plain, and not a third party.
     */
    'secret' => env('PLAIN_SECRET'),

];
