name: Check & fix styling

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:

permissions:
  contents: write

jobs:
  pint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: pint

      - name: Run Laravel Pint
        run: pint --preset laravel

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
